cidades_estados = {
    "São Paulo": "São Paulo",
    "Campinas": "São Paulo",
    "Rio de Janeiro": "Rio de Janeiro",
    "Niterói": "Rio de Janeiro",
    "Belo Horizonte": "Minas Gerais",
    "Uberlândia": "Minas Gerais",
    "Salvador": "Bahia",
    "Feira de Santana": "Bahia",
    "Fortaleza": "Ceará",
    "Caucaia": "Ceará",
    "Curitiba": "Paraná",
    "Londrina": "Paraná",
    "Porto Alegre": "Rio Grande do Sul",
    "Caxias do Sul": "Rio Grande do Sul",
    "Recife": "Pernambuco",
    "Caruaru": "Pernambuco",
    "Brasília": "Distrito Federal",
    "Taguatinga": "Distrito Federal",
    "Goiânia": "Goiás",
    "Aparecida de Goiânia": "Goiás",
    "Manaus": "Amazonas",
    "Itacoatiara": "Amazonas",
}
estados = list(set(cidades_estados.values()))
print(estados)